name: E2E Pytest Selenium Allure - Integrador

on:
  push:
    branches: ["alumno/sbarriosr"]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest-xdist pytest-cov allure-pytest

      - name: Run E2E tests with Allure, Coverage and 2 Workers
        run: |
          python -m pytest tests/integrador/test_suite_integrador.py -n 2

      - name: Upload Allure raw results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results/

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report/

      - name: Upload evidencias (Artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: evidencias
          path: artifacts/
